// ============================================================
//  OmniPrep — js/questions.js
//  Full UTME question bank.
//  English Language: 60 questions
//  All other subjects: 40 questions each
//  Import this file in simulator.html
// ============================================================

const QUESTIONS = {

  // ════════════════════════════════════════
  // ENGLISH LANGUAGE — 60 Questions
  // ════════════════════════════════════════
  "English Language": [
    // Comprehension & Vocabulary
    { q: "Choose the word most nearly opposite in meaning to <em>GARRULOUS</em>.", opts:["Talkative","Reticent","Verbose","Loquacious"], ans:1 },
    { q: "Choose the word most nearly opposite in meaning to <em>BENEVOLENT</em>.", opts:["Generous","Kind","Malevolent","Charitable"], ans:2 },
    { q: "Choose the word most nearly opposite in meaning to <em>OSTENTATIOUS</em>.", opts:["Modest","Flamboyant","Showy","Pompous"], ans:0 },
    { q: "Choose the word most nearly opposite in meaning to <em>LACONIC</em>.", opts:["Brief","Verbose","Concise","Terse"], ans:1 },
    { q: "Choose the word most nearly opposite in meaning to <em>EPHEMERAL</em>.", opts:["Transient","Fleeting","Eternal","Brief"], ans:2 },
    { q: "Choose the word most nearly opposite in meaning to <em>ACRIMONIOUS</em>.", opts:["Bitter","Hostile","Gentle","Harsh"], ans:2 },
    { q: "Choose the word most nearly opposite in meaning to <em>LOQUACIOUS</em>.", opts:["Chatty","Taciturn","Verbose","Talkative"], ans:1 },
    { q: "Choose the word most nearly opposite in meaning to <em>MAGNANIMOUS</em>.", opts:["Generous","Noble","Petty","Forgiving"], ans:2 },
    { q: "Choose the word most nearly opposite in meaning to <em>PRUDENT</em>.", opts:["Careful","Wise","Reckless","Cautious"], ans:2 },
    { q: "Choose the word most nearly opposite in meaning to <em>SYCOPHANTIC</em>.", opts:["Flattering","Fawning","Sincere","Servile"], ans:2 },

    // Grammar & Usage
    { q: "Select the option that best completes: The manager, together with his staff, _____ present.", opts:["were","are","was","have been"], ans:2 },
    { q: "Select the option that best completes: Neither the students nor the teacher _____ aware of the change.", opts:["were","are","was","have been"], ans:2 },
    { q: "Select the option that best completes: Each of the boys _____ given a prize.", opts:["were","are","was","have been"], ans:2 },
    { q: "Select the option that best completes: The committee _____ yet to reach a decision.", opts:["have","has","were","are"], ans:1 },
    { q: "Select the option that best completes: If I _____ you, I would accept the offer.", opts:["am","was","were","had been"], ans:2 },
    { q: "Select the option that best completes: By the time he arrived, we _____ for two hours.", opts:["waited","have waited","had been waiting","were waiting"], ans:2 },
    { q: "Select the option that best completes: She is one of those students who _____ always late.", opts:["is","was","are","has been"], ans:2 },
    { q: "Select the option that best completes: The news _____ very disturbing.", opts:["were","are","is","have been"], ans:2 },
    { q: "Select the option that best completes: No sooner _____ he arrived than it started raining.", opts:["did","had","has","was"], ans:1 },
    { q: "Select the option that best completes: I suggest that he _____ the matter immediately.", opts:["addresses","address","addressed","is addressing"], ans:1 },

    // Figures of Speech
    { q: "Identify the figure of speech: <em>The wind whispered through the trees.</em>", opts:["Simile","Hyperbole","Personification","Onomatopoeia"], ans:2 },
    { q: "Identify the figure of speech: <em>Life is a journey with no map.</em>", opts:["Simile","Metaphor","Irony","Alliteration"], ans:1 },
    { q: "Identify the figure of speech: <em>He is as brave as a lion.</em>", opts:["Metaphor","Simile","Hyperbole","Personification"], ans:1 },
    { q: "Identify the figure of speech: <em>I have told you a million times.</em>", opts:["Simile","Metaphor","Hyperbole","Irony"], ans:2 },
    { q: "Identify the figure of speech: <em>The bees buzzed busily in the bright blooms.</em>", opts:["Assonance","Alliteration","Onomatopoeia","Rhyme"], ans:1 },
    { q: "Identify the figure of speech: <em>The thunder roared and the lightning danced.</em>", opts:["Simile","Irony","Personification","Hyperbole"], ans:2 },
    { q: "Identify the figure of speech: <em>What a fine friend you turned out to be!</em> (said sarcastically)", opts:["Irony","Simile","Metaphor","Hyperbole"], ans:0 },
    { q: "Identify the figure of speech: <em>The hissing snake slithered silently.</em>", opts:["Alliteration","Onomatopoeia","Both A and B","Assonance"], ans:2 },
    { q: "Identify the figure of speech: <em>Death, be not proud.</em>", opts:["Simile","Apostrophe","Metaphor","Irony"], ans:1 },
    { q: "Identify the figure of speech: <em>Time is a thief that steals our youth.</em>", opts:["Simile","Personification","Metaphor","Alliteration"], ans:2 },

    // Sentence Structure
    { q: "Which is a complex sentence?", opts:["She sang and danced.","He is tall but slim.","Because she was tired, she slept early.","Run fast or miss the bus."], ans:2 },
    { q: "Which is a compound sentence?", opts:["Although he was tired, he worked.","She reads books and he plays football.","The boy who came yesterday left early.","Running fast, she caught the bus."], ans:1 },
    { q: "Which sentence contains a dangling modifier?", opts:["Running fast, John caught the bus.","Running fast, the bus was caught.","John, running fast, caught the bus.","The bus was caught by John."], ans:1 },
    { q: "Which sentence is in the passive voice?", opts:["The dog chased the cat.","The cat was chased by the dog.","She is chasing the dog.","He chases dogs daily."], ans:1 },
    { q: "Which sentence contains a misplaced modifier?", opts:["She almost drove her children to school every day.","She drove her children to school almost every day.","Almost every day she drove her children to school.","Her children were driven to school every day."], ans:0 },
    { q: "Identify the type: <em>The man who came yesterday is my uncle.</em>", opts:["Simple","Compound","Complex","Compound-complex"], ans:2 },
    { q: "Which sentence has correct subject-verb agreement?", opts:["The data is clear.","The data are clear.","Both A and B are correct.","Neither A nor B is correct."], ans:2 },
    { q: "Which sentence uses the apostrophe correctly?", opts:["The girl's shoes are dirty.","The girls shoe's are dirty.","The girls' shoe's are dirty.","The girl's shoe's are dirty."], ans:0 },
    { q: "Which is a simple sentence?", opts:["He came and he saw.","Although tired, he worked hard.","He came, he saw, and he conquered.","The soldier came."], ans:3 },
    { q: "Choose the sentence that is NOT a fragment.", opts:["Running down the hill.","After the long meeting.","She finally arrived.","Because he was late."], ans:2 },

    // Direct & Indirect Speech
    { q: "Rewrite in indirect speech: He said, 'I am going to Lagos tomorrow.'", opts:["He said he was going to Lagos the next day.","He said he is going to Lagos tomorrow.","He said he will go to Lagos tomorrow.","He said he went to Lagos the next day."], ans:0 },
    { q: "Rewrite in indirect speech: She said, 'I have finished my work.'", opts:["She said she has finished her work.","She said she had finished her work.","She said she finished her work.","She said she would finish her work."], ans:1 },
    { q: "Rewrite in direct speech: He asked whether she was ready.", opts:["He said, 'Is she ready?'","He said, 'Are you ready?'","He asked, 'Was she ready?'","He asked, 'Were you ready?'"], ans:1 },
    { q: "Choose the correct reported speech: 'Don't go there,' she warned him.", opts:["She warned him not to go there.","She warned him don't go there.","She warned him that he should not go there.","Both A and C"], ans:3 },
    { q: "Rewrite in indirect speech: 'Can you help me?' he asked her.", opts:["He asked her if she could help him.","He asked her can she help him.","He asked her whether she can help him.","He told her to help him."], ans:0 },

    // Comprehension — Passages (simplified single-question format)
    { q: "The word <em>ubiquitous</em> means:", opts:["Rare","Found everywhere","Beautiful","Ancient"], ans:1 },
    { q: "The word <em>meticulous</em> means:", opts:["Careless","Very careful and precise","Quick","Brave"], ans:1 },
    { q: "The word <em>ambiguous</em> means:", opts:["Clear and obvious","Having one clear meaning","Open to more than one interpretation","Completely wrong"], ans:2 },
    { q: "The word <em>tenacious</em> means:", opts:["Weak","Holding firmly to something","Flexible","Careless"], ans:1 },
    { q: "The word <em>gregarious</em> means:", opts:["Lonely","Fond of company","Aggressive","Shy"], ans:1 },

    // Spelling & Usage
    { q: "Choose the correctly spelt word.", opts:["Accomodate","Accommodate","Acommodate","Accommadate"], ans:1 },
    { q: "Choose the correctly spelt word.", opts:["Occurance","Occurrence","Occurence","Occurrance"], ans:1 },
    { q: "Choose the correctly spelt word.", opts:["Liason","Liaison","Liasson","Liasion"], ans:1 },
    { q: "Choose the correctly spelt word.", opts:["Harass","Harrass","Harras","Haras"], ans:0 },
    { q: "Choose the correctly spelt word.", opts:["Millennium","Millenium","Milenium","Millenniun"], ans:0 },
    { q: "Which sentence uses 'affect' correctly?", opts:["The affect was immediate.","The drug will affect your sleep.","She showed no affect.","What affect did it have?"], ans:1 },
    { q: "Which sentence uses 'principal' correctly?", opts:["The principal reason was money.","She had no principals.","The principal is paid annually.","Both A and C"], ans:3 },
    { q: "Which sentence uses 'its' correctly?", opts:["The dog wagged it's tail.","Its a beautiful day.","The cat licked its paw.","Its' time to go."], ans:2 },
    { q: "Choose the correct word: The _____ of the play was unexpected.", opts:["climax","climatic","climactic","climatical"], ans:2 },
    { q: "Choose the correct option: She _____ the book on the table.", opts:["laid","lied","lay","lie"], ans:0 },
  ],

  // ════════════════════════════════════════
  // MATHEMATICS — 40 Questions
  // ════════════════════════════════════════
  "Mathematics": [
    { q: "If S<sub>n</sub> = 3n² + 5n, find the 8th term of the AP.", opts:["48","51","53","50"], ans:3 },
    { q: "Simplify: (√3 + √2)(√3 − √2)", opts:["1","5","√6","√5"], ans:0 },
    { q: "Find x if log₂(x + 3) = 4.", opts:["11","13","12","16"], ans:1 },
    { q: "A circle has area 154 cm². Find its circumference. (π = 22/7)", opts:["22 cm","44 cm","66 cm","88 cm"], ans:1 },
    { q: "If 2x − 3y = 7 and x + y = 6, find x.", opts:["3","4","5","6"], ans:2 },
    { q: "Evaluate: ∫(2x + 3) dx from 0 to 2.", opts:["10","12","8","14"], ans:0 },
    { q: "A bag has 4 red and 6 blue balls. Two drawn without replacement. P(both red)?", opts:["2/15","4/15","1/6","2/9"], ans:0 },
    { q: "Find the gradient of the line through (2, 5) and (4, 11).", opts:["2","3","4","6"], ans:1 },
    { q: "Find the 10th term of the GP: 2, 6, 18, …", opts:["2×3⁹","3×2⁹","2×9³","6×3⁸"], ans:0 },
    { q: "Solve: |2x − 1| = 5", opts:["x = 3 only","x = −2 only","x = 3 or x = −2","x = 2 or x = −3"], ans:2 },
    { q: "Find the equation of a line with gradient 3 passing through (1, 2).", opts:["y = 3x − 1","y = 3x + 1","y = 3x − 2","y = 3x + 2"], ans:0 },
    { q: "Simplify: (2³ × 2⁵) ÷ 2⁴", opts:["2²","2⁴","2⁶","2⁸"], ans:1 },
    { q: "A man travels 60 km in 1.5 hours. What is his average speed?", opts:["30 km/h","40 km/h","45 km/h","50 km/h"], ans:1 },
    { q: "Find the HCF of 24, 36, and 48.", opts:["6","8","12","24"], ans:2 },
    { q: "Solve: 3x² − 5x − 2 = 0", opts:["x = 2 or x = −1/3","x = −2 or x = 1/3","x = 2 or x = 1/3","x = −2 or x = −1/3"], ans:0 },
    { q: "The sum of angles in a pentagon is:", opts:["360°","450°","540°","720°"], ans:2 },
    { q: "If f(x) = 2x² − 3x + 1, find f(2).", opts:["3","5","7","9"], ans:0 },
    { q: "Simplify: (3a²b³)² ÷ 9a³b²", opts:["a b⁴","a²b⁴","ab⁴","a³b⁶"], ans:0 },
    { q: "The mean of 5 numbers is 12. If four of them are 10, 14, 8, 16, find the fifth.", opts:["10","12","14","16"], ans:1 },
    { q: "Convert 0.000045 to standard form.", opts:["4.5 × 10⁻⁵","4.5 × 10⁻⁴","4.5 × 10⁵","45 × 10⁻⁶"], ans:0 },
    { q: "Find the area of a triangle with base 10 cm and height 6 cm.", opts:["30 cm²","60 cm²","16 cm²","48 cm²"], ans:0 },
    { q: "If log 2 = 0.3010, find log 8.", opts:["0.6020","0.9030","0.3010","2.408"], ans:1 },
    { q: "A rectangle has perimeter 36 cm. If its length is 10 cm, find its width.", opts:["6 cm","7 cm","8 cm","9 cm"], ans:2 },
    { q: "Expand: (x + 3)(x − 2)", opts:["x² + x − 6","x² − x − 6","x² + 5x − 6","x² − 5x + 6"], ans:0 },
    { q: "Find dy/dx if y = 4x³ − 2x + 5.", opts:["12x² − 2","12x² + 2","4x² − 2","12x³ − 2"], ans:0 },
    { q: "A circle has radius 7 cm. Find its area. (π = 22/7)", opts:["44 cm²","154 cm²","22 cm²","308 cm²"], ans:1 },
    { q: "Solve: 2ˣ = 32", opts:["3","4","5","6"], ans:2 },
    { q: "In how many ways can 5 people sit in a row?", opts:["25","60","120","20"], ans:2 },
    { q: "The LCM of 12 and 18 is:", opts:["6","18","36","72"], ans:2 },
    { q: "If the exterior angle of a regular polygon is 45°, how many sides does it have?", opts:["6","7","8","9"], ans:2 },
    { q: "Evaluate: ²⁵C₂", opts:["300","600","625","50"], ans:0 },
    { q: "Find the midpoint of the line joining (−2, 4) and (6, −2).", opts:["(2, 1)","(4, 1)","(2, 2)","(4, 2)"], ans:0 },
    { q: "A car depreciates by 10% each year. If it costs ₦500,000 new, what is its value after 2 years?", opts:["₦400,000","₦405,000","₦410,000","₦450,000"], ans:1 },
    { q: "Solve the inequality: 3x − 4 > 5", opts:["x > 1","x > 2","x > 3","x > 4"], ans:2 },
    { q: "Find the distance between points (1, 2) and (4, 6).", opts:["3","4","5","6"], ans:2 },
    { q: "What is the value of sin 30°?", opts:["√3/2","1/2","√2/2","1"], ans:1 },
    { q: "A cylinder has radius 3.5 cm and height 10 cm. Find its volume. (π = 22/7)", opts:["385 cm³","770 cm³","154 cm³","308 cm³"], ans:0 },
    { q: "Simplify: (1/2 + 1/3) ÷ (1/4)", opts:["5/24","10/3","5/6","2/3"], ans:1 },
    { q: "If P(A) = 0.3 and P(B) = 0.5 and A, B are independent, find P(A and B).", opts:["0.8","0.15","0.35","0.2"], ans:1 },
    { q: "The angle subtended by an arc at the centre is 120°. Find the angle at the circumference.", opts:["120°","60°","240°","30°"], ans:1 },
  ],

  // ════════════════════════════════════════
  // PHYSICS — 40 Questions
  // ════════════════════════════════════════
  "Physics": [
    { q: "A 5 kg body moves at 4 m/s. Its kinetic energy is:", opts:["10 J","20 J","40 J","80 J"], ans:2 },
    { q: "Which is a vector quantity?", opts:["Speed","Mass","Temperature","Velocity"], ans:3 },
    { q: "SI unit of electric resistance:", opts:["Ampere","Volt","Ohm","Farad"], ans:2 },
    { q: "A wave has frequency 50 Hz and wavelength 2 m. Its speed is:", opts:["25 m/s","50 m/s","100 m/s","200 m/s"], ans:2 },
    { q: "An object in equilibrium has net force:", opts:["Maximum","Minimum","Zero","Constant"], ans:2 },
    { q: "Image formed by a plane mirror:", opts:["Real and inverted","Virtual and erect","Real and erect","Virtual and inverted"], ans:1 },
    { q: "Ohm's law: current is proportional to:", opts:["Resistance","Power","Voltage","Charge"], ans:2 },
    { q: "Half-life 20 years. Fraction remaining after 60 years:", opts:["1/4","1/6","1/8","1/16"], ans:2 },
    { q: "A pool appears shallower due to:", opts:["Reflection","Diffraction","Refraction","Dispersion"], ans:2 },
    { q: "Work done is zero when angle between force and displacement is:", opts:["0°","45°","90°","180°"], ans:2 },
    { q: "The unit of power is:", opts:["Joule","Newton","Watt","Pascal"], ans:2 },
    { q: "Which type of wave requires a medium to travel?", opts:["Electromagnetic","Light","Sound","Radio"], ans:2 },
    { q: "The acceleration due to gravity on Earth is approximately:", opts:["9.8 m/s","9.8 m/s²","10 m/s","10 m/s³"], ans:1 },
    { q: "Which of these is a scalar quantity?", opts:["Force","Displacement","Velocity","Speed"], ans:3 },
    { q: "The phenomenon of light bending around obstacles is:", opts:["Reflection","Refraction","Diffraction","Dispersion"], ans:2 },
    { q: "A body thrown horizontally undergoes:", opts:["Uniform motion only","Free fall only","Both horizontal uniform motion and vertical free fall","Circular motion"], ans:2 },
    { q: "The SI unit of electric charge is:", opts:["Volt","Ampere","Coulomb","Farad"], ans:2 },
    { q: "Which of these is NOT a renewable energy source?", opts:["Solar","Wind","Coal","Hydro"], ans:2 },
    { q: "The principle of conservation of energy states that energy:", opts:["Can be created","Can be destroyed","Can neither be created nor destroyed","Changes form only in mechanical systems"], ans:2 },
    { q: "What happens to resistance when temperature increases in a conductor?", opts:["Decreases","Increases","Remains constant","First increases then decreases"], ans:1 },
    { q: "The focal length of a concave mirror is:", opts:["Negative","Positive","Zero","Depends on the object"], ans:0 },
    { q: "Which particle has no charge?", opts:["Proton","Electron","Neutron","Alpha particle"], ans:2 },
    { q: "The transformer works on the principle of:", opts:["Self-induction","Mutual induction","Electromagnetic induction","Magnetic flux"], ans:1 },
    { q: "A body of mass 2 kg is lifted to a height of 5 m. Its potential energy is: (g = 10 m/s²)", opts:["10 J","50 J","100 J","25 J"], ans:2 },
    { q: "Which colour of light has the highest frequency?", opts:["Red","Yellow","Violet","Green"], ans:2 },
    { q: "Ultrasonic waves have frequency:", opts:["Below 20 Hz","Between 20 Hz and 20 kHz","Above 20 kHz","Exactly 20 kHz"], ans:2 },
    { q: "The law of floatation states that a floating body displaces:", opts:["Its own volume of fluid","Its own weight of fluid","More fluid than its weight","Less fluid than its weight"], ans:1 },
    { q: "In a simple pendulum, the period depends on:", opts:["Mass of the bob","Length of the string","Amplitude of swing","All of the above"], ans:1 },
    { q: "The speed of light in a vacuum is approximately:", opts:["3 × 10⁶ m/s","3 × 10⁸ m/s","3 × 10¹⁰ m/s","3 × 10⁴ m/s"], ans:1 },
    { q: "Which of the following is an insulator?", opts:["Copper","Aluminium","Rubber","Iron"], ans:2 },
    { q: "The turning effect of a force is called:", opts:["Tension","Momentum","Torque","Impulse"], ans:2 },
    { q: "In a step-up transformer, the secondary coil has:", opts:["Fewer turns than the primary","More turns than the primary","Equal turns to the primary","No turns"], ans:1 },
    { q: "Which radiation is most penetrating?", opts:["Alpha","Beta","Gamma","X-ray"], ans:2 },
    { q: "The pressure at the bottom of a liquid column depends on:", opts:["The cross-section of the container","The density of the liquid and the height","Only the height of the liquid","Only the density of the liquid"], ans:1 },
    { q: "In photoelectric effect, increasing light intensity increases:", opts:["Energy of photoelectrons","Frequency of light","Number of photoelectrons emitted","Stopping potential"], ans:2 },
    { q: "A convex lens is also called:", opts:["Diverging lens","Converging lens","Concave lens","Plano-concave lens"], ans:1 },
    { q: "The SI unit of frequency is:", opts:["Decibel","Hertz","Watt","Pascal"], ans:1 },
    { q: "Newton's third law states that:", opts:["F = ma","Every action has an equal and opposite reaction","An object remains at rest unless acted upon","Energy is conserved"], ans:1 },
    { q: "Which instrument measures atmospheric pressure?", opts:["Thermometer","Barometer","Hygrometer","Manometer"], ans:1 },
    { q: "The energy stored in a capacitor is given by:", opts:["QV","½QV","½CV²","CV"], ans:2 },
  ],

  // ════════════════════════════════════════
  // CHEMISTRY — 40 Questions
  // ════════════════════════════════════════
  "Chemistry": [
    { q: "Which is the oxide of a non-metal?", opts:["Na₂O","MgO","SO₃","CaO"], ans:2 },
    { q: "Atomic number 17 belongs to Group:", opts:["I","VI","VII","VIII"], ans:2 },
    { q: "Gas produced when zinc reacts with dilute HCl:", opts:["Oxygen","Chlorine","Hydrogen","Carbon dioxide"], ans:2 },
    { q: "IUPAC name of CH₃CH₂OH:", opts:["Methanol","Propanol","Ethanol","Butanol"], ans:2 },
    { q: "Avogadro's number:", opts:["6.02×10²²","6.02×10²³","6.02×10²⁴","6.02×10²⁵"], ans:1 },
    { q: "Bond present in NaCl:", opts:["Covalent","Ionic","Metallic","Hydrogen"], ans:1 },
    { q: "pH of neutral solution at 25°C:", opts:["0","7","14","1"], ans:1 },
    { q: "Converting sugar to alcohol is called:", opts:["Oxidation","Hydrolysis","Fermentation","Polymerisation"], ans:2 },
    { q: "Which is an allotrope of carbon?", opts:["Silicon","Diamond","Graphite","Both B and C"], ans:3 },
    { q: "Molar mass of H₂SO₄:", opts:["96 g/mol","98 g/mol","100 g/mol","94 g/mol"], ans:1 },
    { q: "The process of converting a liquid to vapour below its boiling point is:", opts:["Boiling","Condensation","Evaporation","Sublimation"], ans:2 },
    { q: "Which of these is a mixture?", opts:["Water","Salt","Air","Carbon dioxide"], ans:2 },
    { q: "The number of electrons in a neutral atom of Carbon-12 is:", opts:["6","12","8","4"], ans:0 },
    { q: "Which gas turns limewater milky?", opts:["Hydrogen","Oxygen","Carbon dioxide","Nitrogen"], ans:2 },
    { q: "The oxidation state of oxygen in H₂O₂ is:", opts:["-1","−2","+1","+2"], ans:0 },
    { q: "Rusting of iron is an example of:", opts:["Reduction","Oxidation","Neutralisation","Hydrolysis"], ans:1 },
    { q: "The chemical formula for ammonia is:", opts:["NH₄","NH₃","N₂H₄","NO₂"], ans:1 },
    { q: "Which of the following is a noble gas?", opts:["Nitrogen","Chlorine","Argon","Fluorine"], ans:2 },
    { q: "Electrolysis of brine produces:", opts:["Hydrogen and oxygen","Chlorine, hydrogen and sodium hydroxide","Oxygen and sodium","Chlorine and water"], ans:1 },
    { q: "What is the chemical name of common salt?", opts:["Sodium carbonate","Sodium chloride","Sodium hydroxide","Sodium sulphate"], ans:1 },
    { q: "Which indicator is used in titrations?", opts:["Litmus","Methyl orange","Universal indicator","Both A and B"], ans:3 },
    { q: "The law of conservation of mass states that:", opts:["Mass is always lost in reactions","Mass can be created","Total mass of reactants equals total mass of products","Energy equals mass"], ans:2 },
    { q: "Which metal is most reactive?", opts:["Gold","Copper","Sodium","Iron"], ans:2 },
    { q: "The catalyst in the Haber process for making ammonia is:", opts:["Platinum","Iron","Vanadium pentoxide","Nickel"], ans:1 },
    { q: "Which type of radiation is emitted when a neutron decays into a proton?", opts:["Alpha","Beta","Gamma","X-ray"], ans:1 },
    { q: "What is the formula for glucose?", opts:["C₆H₁₂O₆","C₁₂H₂₂O₁₁","C₂H₅OH","CH₃COOH"], ans:0 },
    { q: "Which property is characteristic of metals?", opts:["Poor conductor of heat","Brittle","Good conductor of electricity","Non-lustrous"], ans:2 },
    { q: "The chemical formula for calcium carbonate is:", opts:["CaCO₃","CaCl₂","Ca(OH)₂","CaSO₄"], ans:0 },
    { q: "In the periodic table, elements in the same period have the same:", opts:["Number of electrons","Number of valence electrons","Number of electron shells","Atomic mass"], ans:2 },
    { q: "What type of reaction is: acid + base → salt + water?", opts:["Decomposition","Neutralisation","Displacement","Combination"], ans:1 },
    { q: "The molecular formula of ethene is:", opts:["CH₄","C₂H₄","C₂H₆","C₂H₂"], ans:1 },
    { q: "Which of the following is a strong acid?", opts:["Acetic acid","Citric acid","Hydrochloric acid","Carbonic acid"], ans:2 },
    { q: "Isotopes of an element have the same:", opts:["Mass number","Number of neutrons","Atomic number","Atomic mass"], ans:2 },
    { q: "The process by which plants absorb water through their roots is:", opts:["Osmosis","Diffusion","Active transport","Evaporation"], ans:0 },
    { q: "Which gas is produced when metals react with dilute acids?", opts:["Oxygen","Carbon dioxide","Hydrogen","Nitrogen"], ans:2 },
    { q: "The formula for sodium hydroxide is:", opts:["NaCl","NaOH","Na₂CO₃","Na₂SO₄"], ans:1 },
    { q: "In a redox reaction, oxidation involves:", opts:["Gain of electrons","Loss of electrons","Gain of protons","Loss of protons"], ans:1 },
    { q: "What is the boiling point of water at standard pressure?", opts:["0°C","37°C","100°C","212°F and 100°C"], ans:3 },
    { q: "The monomer of polyethylene is:", opts:["Ethane","Ethene","Ethanol","Ethanoic acid"], ans:1 },
    { q: "Galvanisation involves coating iron with:", opts:["Tin","Copper","Zinc","Chromium"], ans:2 },
  ],

  // ════════════════════════════════════════
  // BIOLOGY — 40 Questions
  // ════════════════════════════════════════
  "Biology": [
    { q: "Powerhouse of the cell:", opts:["Nucleus","Ribosome","Mitochondria","Chloroplast"], ans:2 },
    { q: "Universal blood donor group:", opts:["A","B","AB","O"], ans:3 },
    { q: "Photosynthesis takes place in the:", opts:["Mitochondria","Nucleus","Chloroplast","Cytoplasm"], ans:2 },
    { q: "Scientific name of man:", opts:["Homo erectus","Homo sapiens","Homo habilis","Homo heidelbergensis"], ans:1 },
    { q: "DNA is found in the:", opts:["Cell membrane","Cytoplasm","Nucleus","Ribosome"], ans:2 },
    { q: "Which is NOT a function of the liver?", opts:["Detoxification","Bile production","Insulin secretion","Glycogen storage"], ans:2 },
    { q: "Osmosis: water moves from region of:", opts:["High solute to low","Low water potential to high","High water potential to low","Low concentration to high"], ans:2 },
    { q: "Part of brain controlling balance:", opts:["Cerebrum","Cerebellum","Medulla","Thalamus"], ans:1 },
    { q: "Meiosis results in:", opts:["2 identical cells","4 identical cells","2 genetically different cells","4 genetically different cells"], ans:3 },
    { q: "Enzyme breaking starch in the mouth:", opts:["Pepsin","Lipase","Amylase","Trypsin"], ans:2 },
    { q: "The basic unit of life is:", opts:["Tissue","Organ","Cell","Organism"], ans:2 },
    { q: "Which organelle is responsible for protein synthesis?", opts:["Mitochondria","Ribosome","Golgi apparatus","Vacuole"], ans:1 },
    { q: "Transpiration in plants occurs mainly through:", opts:["Roots","Stems","Stomata","Lenticels"], ans:2 },
    { q: "Which vitamin is produced when the skin is exposed to sunlight?", opts:["Vitamin A","Vitamin B","Vitamin C","Vitamin D"], ans:3 },
    { q: "The process by which organisms maintain a stable internal environment is:", opts:["Homeostasis","Osmoregulation","Thermoregulation","Excretion"], ans:0 },
    { q: "Which blood component is responsible for clotting?", opts:["Red blood cells","White blood cells","Platelets","Plasma"], ans:2 },
    { q: "The largest organ in the human body is:", opts:["Liver","Lung","Skin","Heart"], ans:2 },
    { q: "In which phase of mitosis do chromosomes line up at the equator?", opts:["Prophase","Metaphase","Anaphase","Telophase"], ans:1 },
    { q: "Which of the following is a monocot plant?", opts:["Mango","Maize","Beans","Groundnut"], ans:1 },
    { q: "The nitrogenous waste product in urine is:", opts:["Urea","Uric acid","Ammonia","Creatine"], ans:0 },
    { q: "Which disease is caused by the Plasmodium parasite?", opts:["Typhoid","Cholera","Malaria","Tuberculosis"], ans:2 },
    { q: "The double helix structure of DNA was discovered by:", opts:["Darwin and Mendel","Watson and Crick","Lamarck and Darwin","Pasteur and Koch"], ans:1 },
    { q: "Which hormone regulates blood sugar level?", opts:["Adrenaline","Thyroxine","Insulin","Oestrogen"], ans:2 },
    { q: "The function of the nephron is:", opts:["Gas exchange","Filtration of blood","Digestion of food","Pumping of blood"], ans:1 },
    { q: "Which of the following is an example of commensalism?", opts:["Tapeworm in gut","Bacteria fixing nitrogen in root nodules","Barnacles on a whale","Lion and zebra"], ans:2 },
    { q: "The process of converting nitrates back to nitrogen gas is:", opts:["Nitrification","Denitrification","Nitrogen fixation","Ammonification"], ans:1 },
    { q: "Which part of the flower produces pollen?", opts:["Stigma","Ovary","Anther","Style"], ans:2 },
    { q: "The adaptive feature of a cactus that reduces water loss is:", opts:["Broad leaves","Spines instead of leaves","Deep roots","All of the above"], ans:3 },
    { q: "Which of these is an example of asexual reproduction?", opts:["Fertilisation","Budding in yeast","Pollination","Mating"], ans:1 },
    { q: "The role of decomposers in an ecosystem is to:", opts:["Produce food","Break down dead organic matter","Consume other animals","Fix nitrogen"], ans:1 },
    { q: "In humans, the sex of an offspring is determined by:", opts:["The mother's chromosome","The father's chromosome","Both parents equally","Neither parent"], ans:1 },
    { q: "Which part of the brain controls involuntary actions like breathing?", opts:["Cerebrum","Cerebellum","Medulla oblongata","Hypothalamus"], ans:2 },
    { q: "Sickle cell anaemia is caused by:", opts:["A virus","A bacterium","A gene mutation","A nutritional deficiency"], ans:2 },
    { q: "The process of engulfing food particles by a cell is called:", opts:["Endocytosis","Exocytosis","Phagocytosis","Pinocytosis"], ans:2 },
    { q: "Which of the following is a secondary consumer?", opts:["Grass","Grasshopper","Frog","Eagle"], ans:2 },
    { q: "The scientific study of fungi is:", opts:["Bacteriology","Virology","Mycology","Botany"], ans:2 },
    { q: "Which vitamin deficiency causes scurvy?", opts:["Vitamin A","Vitamin B","Vitamin C","Vitamin D"], ans:2 },
    { q: "The enzyme pepsin is produced in the:", opts:["Mouth","Stomach","Small intestine","Pancreas"], ans:1 },
    { q: "An organism that can make its own food is called:", opts:["Heterotroph","Autotroph","Decomposer","Carnivore"], ans:1 },
    { q: "The function of haemoglobin is to:", opts:["Fight infection","Transport oxygen","Produce antibodies","Clot blood"], ans:1 },
  ],

  // ════════════════════════════════════════
  // ECONOMICS — 40 Questions
  // ════════════════════════════════════════
  "Economics": [
    { q: "Which is NOT a factor of production?", opts:["Land","Labour","Money","Capital"], ans:2 },
    { q: "Supply increases, demand constant — equilibrium price will:", opts:["Rise","Fall","Remain same","Double"], ans:1 },
    { q: "GDP stands for:", opts:["Gross Domestic Product","General Domestic Price","Gross Domestic Price","General Development Product"], ans:0 },
    { q: "Inflation is best described as:", opts:["Rise in unemployment","Fall in interest rates","Sustained rise in price level","Fall in export value"], ans:2 },
    { q: "Unemployment during economic downturns:", opts:["Frictional","Structural","Cyclical","Seasonal"], ans:2 },
    { q: "Price elasticity of demand measures:", opts:["How price changes with income","Responsiveness of demand to price","How supply responds to price","Responsiveness of price to supply"], ans:1 },
    { q: "A monopoly exists when:", opts:["Many sellers","One seller many buyers","Two sellers","Many buyers and sellers"], ans:1 },
    { q: "Circular flow of income involves:", opts:["Households and firms","Government only","Banks only","All of the above"], ans:3 },
    { q: "Which is a merit good?", opts:["Cigarettes","Alcohol","Education","Luxury cars"], ans:2 },
    { q: "Opportunity cost is:", opts:["Monetary cost","Next best alternative foregone","Total cost","Marginal cost"], ans:1 },
    { q: "Which of the following best describes 'barter'?", opts:["Buying with money","Exchange of goods for goods","Lending with interest","Saving in a bank"], ans:1 },
    { q: "The term 'laissez-faire' in economics means:", opts:["Government controls all business","Free market with minimal government intervention","High taxation","Central planning"], ans:1 },
    { q: "A budget deficit occurs when:", opts:["Revenue exceeds expenditure","Expenditure exceeds revenue","Revenue equals expenditure","Imports exceed exports"], ans:1 },
    { q: "Which of these is an indirect tax?", opts:["Income tax","Company tax","VAT","Capital gains tax"], ans:2 },
    { q: "The demand curve slopes downward because:", opts:["As price rises, demand rises","As price falls, demand falls","As price rises, demand falls","Price and demand are unrelated"], ans:2 },
    { q: "Which of the following causes cost-push inflation?", opts:["Increase in money supply","Rise in government spending","Rise in production costs","Decrease in interest rates"], ans:2 },
    { q: "A progressive tax system means:", opts:["Everyone pays the same amount","Higher income earners pay a higher percentage","Lower income earners pay more","Tax is collected only from businesses"], ans:1 },
    { q: "The Nigerian national budget is prepared by:", opts:["Central Bank of Nigeria","National Assembly","Federal Ministry of Finance","The President alone"], ans:2 },
    { q: "Stagflation refers to:", opts:["Low inflation and high growth","High inflation and high unemployment","High growth and low unemployment","Low inflation and low growth"], ans:1 },
    { q: "Which of these is NOT a function of commercial banks?", opts:["Accepting deposits","Giving loans","Printing currency","Foreign exchange"], ans:2 },
    { q: "The law of diminishing returns states that:", opts:["Adding more capital always increases output","Beyond a point, adding more of a variable factor reduces marginal product","Output always increases with more inputs","Prices fall as production increases"], ans:1 },
    { q: "ECOWAS was established primarily to:", opts:["Promote military cooperation","Promote economic integration in West Africa","Control oil prices","Establish a single currency"], ans:1 },
    { q: "Which type of economy is practised in Nigeria?", opts:["Pure command","Pure market","Mixed","Traditional"], ans:3 },
    { q: "The central bank controls money supply through:", opts:["Fiscal policy","Monetary policy","Trade policy","Industrial policy"], ans:1 },
    { q: "Comparative advantage in trade means:", opts:["Producing goods at lowest absolute cost","Producing goods at lowest opportunity cost","Importing all goods","Exporting raw materials only"], ans:1 },
    { q: "Which of the following is a public good?", opts:["A car","A loaf of bread","National defence","A mobile phone"], ans:2 },
    { q: "The difference between exports and imports is called:", opts:["Balance of payments","Balance of trade","Current account","Capital account"], ans:1 },
    { q: "Microeconomics deals with:", opts:["The economy as a whole","Individual firms and consumers","National income","International trade"], ans:1 },
    { q: "Which of the following is NOT a characteristic of perfect competition?", opts:["Many buyers and sellers","Homogeneous products","Price maker","Free entry and exit"], ans:2 },
    { q: "Devaluation of a currency makes:", opts:["Exports more expensive","Imports cheaper","Exports cheaper and imports more expensive","Both exports and imports cheaper"], ans:2 },
    { q: "The multiplier effect in economics refers to:", opts:["The increase in tax revenue","The proportional increase in income from an initial injection","The decrease in unemployment","The rise in interest rates"], ans:1 },
    { q: "Which of the following is NOT a goal of macroeconomic policy?", opts:["Full employment","Price stability","Economic growth","Individual profit maximisation"], ans:3 },
    { q: "Nigeria's main source of government revenue is:", opts:["Agriculture","Tourism","Crude oil","Manufacturing"], ans:2 },
    { q: "In a mixed economy, resources are allocated by:", opts:["Government alone","Market forces alone","Both government and market forces","International organisations"], ans:2 },
    { q: "The term 'depreciation' in economics refers to:", opts:["A fall in the value of an asset over time","A fall in the exchange rate","A reduction in government spending","A fall in employment"], ans:0 },
    { q: "Which organisation regulates banks in Nigeria?", opts:["SEC","NAFDAC","CBN","EFCC"], ans:2 },
    { q: "Consumer surplus is:", opts:["The extra profit made by producers","The difference between what consumers are willing to pay and what they actually pay","The tax paid on goods","The cost of production"], ans:1 },
    { q: "Which of these is an example of foreign direct investment?", opts:["Buying shares on the stock exchange","A foreign company building a factory in Nigeria","Sending remittances home","Buying government bonds"], ans:1 },
    { q: "The Phillips curve shows the relationship between:", opts:["Inflation and growth","Unemployment and inflation","Interest rates and investment","Exports and imports"], ans:1 },
    { q: "Which of the following is a supply-side policy?", opts:["Increasing government spending","Reducing interest rates","Cutting income tax to increase work incentive","Printing more money"], ans:2 },
  ],

  // ════════════════════════════════════════
  // GOVERNMENT — 40 Questions
  // ════════════════════════════════════════
  "Government": [
    { q: "Separation of powers was propounded by:", opts:["John Locke","Thomas Hobbes","Montesquieu","Jean-Jacques Rousseau"], ans:2 },
    { q: "Nigeria became a republic in:", opts:["1960","1963","1966","1979"], ans:1 },
    { q: "Federalism: power is:", opts:["Concentrated at centre","Shared between central and component units","Exercised by military","Vested in single party"], ans:1 },
    { q: "Which organ makes laws?", opts:["Executive","Judiciary","Legislature","Civil service"], ans:2 },
    { q: "A constitution easily amended is:", opts:["Rigid","Flexible","Federal","Unitary"], ans:1 },
    { q: "ECOWAS was established in:", opts:["1960","1963","1975","1980"], ans:2 },
    { q: "Judicial independence means:", opts:["Judges make any law","Courts free from executive interference","Lawyers set fees","Judges elected by people"], ans:1 },
    { q: "A pressure group differs from a party in that it:", opts:["Seeks to win elections","Does not seek to form government","Has no members","Has a constitution"], ans:1 },
    { q: "First executive President of Nigeria:", opts:["Nnamdi Azikiwe","Shehu Shagari","Olusegun Obasanjo","Murtala Muhammed"], ans:1 },
    { q: "Rule of law means:", opts:["Military rules","Everyone subject to law","Only leaders above law","Laws made by judges"], ans:1 },
    { q: "The principle of judicial review means:", opts:["Judges can rewrite laws","Courts can declare laws unconstitutional","The executive reviews court decisions","Parliament reviews court decisions"], ans:1 },
    { q: "A unitary state is one where:", opts:["Power is shared between states","All power is concentrated in the central government","Military is in control","There is no constitution"], ans:1 },
    { q: "The concept of sovereignty means:", opts:["A state has supreme authority","A state must obey foreign powers","A state must follow international law","Citizens have all the power"], ans:0 },
    { q: "Universal adult suffrage means:", opts:["Only educated adults can vote","Only property owners can vote","All adults have the right to vote","Only men can vote"], ans:2 },
    { q: "The Nigerian constitution was last revised in:", opts:["1979","1989","1999","2010"], ans:2 },
    { q: "Which of the following is NOT a feature of democracy?", opts:["Free and fair elections","Rule of law","Protection of minority rights","Military rule"], ans:3 },
    { q: "The United Nations was established in:", opts:["1919","1939","1945","1948"], ans:2 },
    { q: "A confederation is:", opts:["A strong central government","A loose alliance of sovereign states","A military alliance","A trade agreement"], ans:1 },
    { q: "The doctrine of checks and balances ensures that:", opts:["One branch of government dominates","Each branch limits the power of the others","The judiciary controls everything","The military oversees government"], ans:1 },
    { q: "Citizenship can be acquired by:", opts:["Birth only","Naturalisation only","Birth or naturalisation","Marriage only"], ans:2 },
    { q: "The first Prime Minister of independent Nigeria was:", opts:["Nnamdi Azikiwe","Obafemi Awolowo","Tafawa Balewa","Ahmadu Bello"], ans:2 },
    { q: "Which tier of government collects VAT in Nigeria?", opts:["Federal","State","Local","All tiers equally"], ans:0 },
    { q: "Proportional representation ensures:", opts:["The majority always wins all seats","Seats are allocated based on proportion of votes received","Only two parties can exist","The President is directly elected"], ans:1 },
    { q: "The African Union (AU) was established in:", opts:["1963","1991","2002","2010"], ans:2 },
    { q: "A by-election is conducted when:", opts:["General elections are held","A seat becomes vacant between general elections","The president dies","A new political party is formed"], ans:1 },
    { q: "Which of the following is a right and not a duty?", opts:["Paying taxes","Defending the country","Freedom of speech","Voting"], ans:2 },
    { q: "The military coup of January 1966 in Nigeria was led by:", opts:["Murtala Muhammed","Yakubu Gowon","Chukwuemeka Odumegwu Ojukwu","Kaduna Nzeogwu"], ans:3 },
    { q: "Parliamentary system differs from presidential system in that:", opts:["Parliament is elected","The executive is accountable to the legislature","There is a president","There is a constitution"], ans:1 },
    { q: "A referendum is:", opts:["An election to choose a leader","A direct vote by the electorate on a specific issue","A vote by parliament only","A military decision"], ans:1 },
    { q: "The power to impeach the President in Nigeria lies with:", opts:["The Supreme Court","The National Assembly","The Attorney-General","The Electoral Commission"], ans:1 },
    { q: "Which of the following is NOT a function of INEC?", opts:["Organising elections","Registering voters","Making laws","Announcing election results"], ans:2 },
    { q: "Colonialism in Africa ended mainly because of:", opts:["Military defeat of colonial powers","Nationalist movements and international pressure","Economic collapse of colonies","Natural disasters"], ans:1 },
    { q: "The policy of apartheid was practised in:", opts:["Kenya","Zimbabwe","South Africa","Zambia"], ans:2 },
    { q: "Which of the following is a characteristic of authoritarian governments?", opts:["Free press","Regular free elections","Suppression of political opposition","Separation of powers"], ans:2 },
    { q: "The concept of 'social contract' was developed by:", opts:["Marx and Engels","Locke, Hobbes and Rousseau","Weber and Durkheim","Plato and Aristotle"], ans:1 },
    { q: "Nigeria's legislative power is vested in the:", opts:["Supreme Court","National Assembly","Federal Executive Council","Joint Federal-State Council"], ans:1 },
    { q: "The Governor-General represented:", opts:["The President","The British Crown","The Prime Minister","The Military"], ans:1 },
    { q: "Checks and balances in Nigeria include:", opts:["Senate confirmation of presidential appointments","Judicial review of laws","Legislative oversight of executive","All of the above"], ans:3 },
    { q: "Which of the following best describes 'statism'?", opts:["Belief in individual freedom","Belief in strong state control over the economy and society","Belief in market forces","Belief in decentralisation"], ans:1 },
    { q: "The International Court of Justice is located in:", opts:["New York","Geneva","The Hague","Brussels"], ans:2 },
  ],

  // ════════════════════════════════════════
  // LITERATURE — 40 Questions
  // ════════════════════════════════════════
  "Literature": [
    { q: "A soliloquy is when a character:", opts:["Speaks to another","Speaks thoughts aloud alone","Whispers to audience","Writes a letter on stage"], ans:1 },
    { q: "'Life is a journey' is an example of:", opts:["Simile","Metaphor","Irony","Alliteration"], ans:1 },
    { q: "The protagonist is:", opts:["The villain","The narrator","The main character","The author"], ans:2 },
    { q: "An epic poem is characterised by:", opts:["Short lyric style","Hero of great stature and grand adventure","Comic elements","Personal emotions of poet"], ans:1 },
    { q: "Denouement refers to:", opts:["Climax","Opening scene","Resolution of plot","Type of poem"], ans:2 },
    { q: "Dramatic irony is when:", opts:["Audience and characters share knowledge","Audience knows something character does not","Character is sarcastic","Plot has surprise ending"], ans:1 },
    { q: "A sonnet has how many lines?", opts:["10","12","14","16"], ans:2 },
    { q: "In medias res means:", opts:["In the middle of things","At the beginning","At the end","Through flashback"], ans:0 },
    { q: "Which is a comedy of manners?", opts:["Macbeth","Hamlet","The Importance of Being Earnest","King Lear"], ans:2 },
    { q: "A round character is one who is:", opts:["Morally good","Complex and fully developed","Never changes","A supporting character"], ans:1 },
    { q: "The term 'flat character' refers to:", opts:["A complex, multi-dimensional character","A simple character with one or two traits","The main character","A villain"], ans:1 },
    { q: "The exposition in a story is:", opts:["The turning point","The background information at the beginning","The climax","The resolution"], ans:1 },
    { q: "Which of the following is an example of alliteration?", opts:["She sells seashells by the seashore","My love is like a red, red rose","All the world's a stage","To be or not to be"], ans:0 },
    { q: "A tragedy ends with:", opts:["A happy resolution","The triumph of the hero","The downfall or death of the protagonist","Marriage"], ans:2 },
    { q: "The term 'stream of consciousness' refers to:", opts:["A narrative technique depicting character's continuous flow of thought","A type of poetry","An element of setting","A literary device using rivers as symbols"], ans:0 },
    { q: "Which of the following is a feature of African oral literature?", opts:["Complex written structure","Communal performance and audience participation","Individual authorship","Silent reading"], ans:1 },
    { q: "An ode is:", opts:["A short narrative poem","A lyric poem addressed to a person or thing","A poem about death","A satirical poem"], ans:1 },
    { q: "The term 'foil' in literature refers to:", opts:["A character who contrasts with the protagonist","A type of irony","A narrative technique","A dramatic monologue"], ans:0 },
    { q: "Which of these is an example of onomatopoeia?", opts:["The sun smiled","He ran like the wind","The bees buzzed","Life is a game"], ans:2 },
    { q: "A Shakespearean sonnet consists of:", opts:["Three quatrains and a couplet","Two octaves","One sestet and one octave","Four tercets"], ans:0 },
    { q: "The term 'catharsis' was used by Aristotle to describe:", opts:["The purging of emotions in the audience","The plot of a tragedy","The role of the chorus","The characterisation in a play"], ans:0 },
    { q: "Which literary device is used when an author addresses an absent or imaginary person?", opts:["Allusion","Apostrophe","Irony","Paradox"], ans:1 },
    { q: "The novel as a literary form originated in:", opts:["Ancient Greece","Medieval Europe","18th century England","20th century America"], ans:2 },
    { q: "A villanelle is a poem with:", opts:["14 lines","19 lines","Varying line counts","Exactly 3 stanzas"], ans:1 },
    { q: "Which of the following is a feature of magical realism?", opts:["Pure fantasy with no real-world elements","Realistic settings with magical or supernatural elements","Historical fiction","Science fiction"], ans:1 },
    { q: "The term 'deus ex machina' refers to:", opts:["A character who controls the plot","An unexpected power or event that suddenly solves a problem","A type of Greek tragedy","A narrative within a narrative"], ans:1 },
    { q: "Which of the following wrote 'Things Fall Apart'?", opts:["Wole Soyinka","Ngugi wa Thiong'o","Chinua Achebe","Christopher Okigbo"], ans:2 },
    { q: "A ballad is characterised by:", opts:["Complex imagery and symbolism","Simple narrative and often a refrain","Strict adherence to sonnet form","Extended metaphors"], ans:1 },
    { q: "The term 'pathetic fallacy' refers to:", opts:["A logical error in a character's reasoning","The attribution of human emotions to nature","A type of tragic error","An unreliable narrator"], ans:1 },
    { q: "Which of the following is an example of a frame narrative?", opts:["Romeo and Juliet","The Canterbury Tales","Paradise Lost","Hamlet"], ans:1 },
    { q: "Satire in literature is used to:", opts:["Praise an individual or society","Criticise and mock human folly and vice","Describe nature","Tell a love story"], ans:1 },
    { q: "The term 'bildungsroman' refers to:", opts:["A political novel","A coming-of-age story","A war narrative","A mystery novel"], ans:1 },
    { q: "An anti-hero is:", opts:["A villain","A protagonist who lacks traditional heroic qualities","A supporting character","A narrator"], ans:1 },
    { q: "Which of the following is a characteristic of modernist literature?", opts:["Linear narrative","Omniscient narrator","Fragmented narrative and stream of consciousness","Traditional heroism"], ans:2 },
    { q: "The term 'archetype' in literature refers to:", opts:["A character unique to one story","A universal symbol, character, or theme","A specific literary technique","A narrative device"], ans:1 },
    { q: "Wole Soyinka was awarded the Nobel Prize for Literature in:", opts:["1976","1981","1986","1991"], ans:2 },
    { q: "A haiku is a Japanese poem with:", opts:["14 lines","3 lines of 5, 7, and 5 syllables","4 stanzas","Rhyming couplets"], ans:1 },
    { q: "The term 'unreliable narrator' refers to:", opts:["A narrator who tells the story from outside","A narrator whose credibility is compromised","A narrator who is omniscient","A narrator who is a minor character"], ans:1 },
    { q: "Which of the following is an example of a motif?", opts:["A single metaphor used once","A recurring element that has symbolic significance","The main theme of a work","A character's flaw"], ans:1 },
    { q: "The conflict in a story can be:", opts:["Only between two characters","Only internal","Man vs man, man vs nature, man vs self, or man vs society","Only physical"], ans:2 },
  ],

  // ════════════════════════════════════════
  // GEOGRAPHY — 40 Questions
  // ════════════════════════════════════════
  "Geography": [
    { q: "The longest river in Africa is:", opts:["Congo","Niger","Zambezi","Nile"], ans:3 },
    { q: "Which is a metamorphic rock?", opts:["Granite","Sandstone","Marble","Limestone"], ans:2 },
    { q: "The Tropic of Cancer is at latitude:", opts:["0°","23.5°N","23.5°S","66.5°N"], ans:1 },
    { q: "Lagos is located in which geopolitical zone?", opts:["North West","South East","South West","South South"], ans:2 },
    { q: "The process of wind erosion is called:", opts:["Attrition","Corrasion","Deflation","Hydraulic action"], ans:2 },
    { q: "Which ocean is the largest?", opts:["Atlantic","Indian","Arctic","Pacific"], ans:3 },
    { q: "Harmattan is caused by:", opts:["South-west monsoon","North-east trade wind","Sea breeze","Convectional currents"], ans:1 },
    { q: "A contour line joins points of equal:", opts:["Temperature","Rainfall","Altitude","Pressure"], ans:2 },
    { q: "The savanna vegetation is found in which climate zone?", opts:["Equatorial","Tropical","Mediterranean","Desert"], ans:1 },
    { q: "Urban settlement is characterised by:", opts:["Low population density","Predominantly agricultural activity","High population density","Scattered houses"], ans:2 },
    { q: "The highest mountain in Africa is:", opts:["Mount Kenya","Mount Kilimanjaro","Ruwenzori","Atlas Mountains"], ans:1 },
    { q: "Which of the following is a renewable resource?", opts:["Coal","Petroleum","Solar energy","Natural gas"], ans:2 },
    { q: "The International Date Line is located at:", opts:["0° longitude","90° East","180° longitude","90° West"], ans:2 },
    { q: "The process by which rocks are broken down in situ is called:", opts:["Erosion","Transportation","Weathering","Deposition"], ans:2 },
    { q: "Which of the following is the capital of Nigeria?", opts:["Lagos","Kano","Abuja","Ibadan"], ans:2 },
    { q: "A delta is formed at:", opts:["The source of a river","Where two rivers meet","The mouth of a river","The middle of a river"], ans:2 },
    { q: "The equator passes through which African country?", opts:["Nigeria","Ghana","Kenya","South Africa"], ans:2 },
    { q: "Which type of climate is characterised by hot dry summers and warm wet winters?", opts:["Equatorial","Tropical","Mediterranean","Temperate"], ans:2 },
    { q: "Population density is calculated as:", opts:["Total population × Area","Total population ÷ Area","Area ÷ Total population","Birth rate − Death rate"], ans:1 },
    { q: "The River Niger enters the sea through:", opts:["The Gulf of Guinea","The Atlantic Ocean directly","The Niger Delta","The Bight of Benin"], ans:2 },
    { q: "A watershed is:", opts:["An area where water is stored","The high ground dividing two drainage basins","A man-made dam","A flooded valley"], ans:1 },
    { q: "Which of the following is NOT a feature of equatorial climate?", opts:["High rainfall throughout the year","High temperatures","Distinct dry season","Dense forest"], ans:2 },
    { q: "The main cause of desertification in the Sahel region is:", opts:["Flooding","Overgrazing and deforestation","Earthquakes","Volcanic eruptions"], ans:1 },
    { q: "A plateau is:", opts:["A highland with a flat top","A deep valley","A coastal plain","A river floodplain"], ans:0 },
    { q: "The term 'urbanisation' refers to:", opts:["Movement from urban to rural areas","Increase in the proportion of people living in urban areas","Building new villages","Industrial development in rural areas"], ans:1 },
    { q: "Which of the following is an igneous rock?", opts:["Limestone","Sandstone","Granite","Slate"], ans:2 },
    { q: "The great circle that divides the earth into Northern and Southern hemispheres is:", opts:["Tropic of Cancer","Tropic of Capricorn","Equator","Prime Meridian"], ans:2 },
    { q: "Abuja became the capital of Nigeria in:", opts:["1960","1976","1991","2000"], ans:2 },
    { q: "Which of the following is a pull factor in rural-urban migration?", opts:["Drought","Poor healthcare","Better employment opportunities","Ethnic conflicts"], ans:2 },
    { q: "The process by which water vapour cools and turns to liquid is:", opts:["Evaporation","Transpiration","Condensation","Precipitation"], ans:2 },
    { q: "Which of the following is NOT a type of rainfall?", opts:["Convectional","Relief","Frontal","Coastal"], ans:3 },
    { q: "A fjord is:", opts:["A long narrow sea inlet between cliffs","A flat coastal plain","A type of volcano","A river estuary"], ans:0 },
    { q: "The Amazon rainforest is located in:", opts:["Africa","Asia","South America","Australia"], ans:2 },
    { q: "Which of the following is a characteristic of subsistence farming?", opts:["Large-scale production for export","Mechanised farming","Production mainly for family consumption","Use of chemical fertilisers"], ans:2 },
    { q: "The term 'GNP' stands for:", opts:["Gross National Product","General National Price","Gross Natural Product","Government National Policy"], ans:0 },
    { q: "Latitude lines run:", opts:["North to south","East to west","Diagonally","In circles around the poles"], ans:1 },
    { q: "The Sahara Desert is located in:", opts:["West Africa","East Africa","North Africa","Southern Africa"], ans:2 },
    { q: "A spring tide occurs when:", opts:["The sun and moon are at right angles","The sun and moon are aligned","Only the moon affects the tides","Only the sun affects the tides"], ans:1 },
    { q: "Petroleum is found mainly in which geopolitical zone of Nigeria?", opts:["North Central","South West","South South","North East"], ans:2 },
    { q: "The process of planting trees to restore a forest is called:", opts:["Deforestation","Afforestation","Desertification","Irrigation"], ans:1 },
  ],

};

// Export for use in simulator.html
export { QUESTIONS };
